### ISSUE TITLE
After updating 8-28-2016 US CST errors

### ISSUE THREAD

**Issue by jimgwhit** [nova-framework/bare-app#8]
Getting
```
 InvalidArgumentException (1)
Unable to load the view 'Dogs/Index' on domain 'App'.
```
No routes / views are working.  
Prior all worked good.  

I even did a fresh install, still same error:
```
"Unable to load the view 'Default' on domain 'App'."
```

top error from left side, bottom shows right side but same sort of error.  
seems to be in vendor\nova-framework\system\src\View\Factory.php  

Also on major changes in ver 3.x there are detailed comments, no detailed comments in ver 4 as to how to adjust after an change.

**Comment by LuckyCyborg** [comment]
> Also on major changes in ver 3.x there are detailed comments, no detailed comments in ver 4 as to how to adjust after an change.

You are on a development branch, of course there are no release notes, because there are no pull requests. Also to note that even on future, the **master** branch on Nova 4 will be for development and on the (future) release branches will be notes and/or comments.

Finally, to note that there is no guarantee that Nova 4 present a stability or functionality at all, being considered **pre-alpha** code with a reason, and while I thank you for your will to test it, if Nova 4 break, I recommend you to try again in several days. 

BTW, the "issue" reported cannot be associated with the **bare-app** tree and I can't confirm it.
